apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{ include "app.label" .}}
spec:
  type: {{ .Values.service.type }}
  selector:             
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.service.port }}       
      targetPort: {{ .Values.container.port }}
