apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    {{ include "app.label" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        group: {{ .Values.group }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.container.image }}  
          ports:
            - containerPort: {{ .Values.container.port }}

