apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app.kubernetes.io/version: {{ .Release.Name }}-{{ .Release.Revision }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app: {{ .Values.app.name }}
    group: {{ .Values.app.group }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        group: {{ .Values.app.group }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.container.image }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          env:
            {{- range .Values.app.container.env }}
            - name: {{ .key }}
              value: {{ .value }}
            {{- end }} 
        #   env:
        #     - name: DB_SERVER
        #       value: postgres
        #     - name: POSTGRES_DB
        #       value: kanban
        #     - name: POSTGRES_USER
        #       value: kanban
        #     - name: POSTGRES_PASSWORD
        #       value: kanban
